version: "3.9"

networks:
  kyros-api_kyros-network:
    external: true

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200" 
    networks:
      - kyros-api_kyros-network

